title: Caudal
subtitle: "A fast & powerful event analysis platform"
description: "Caudal is a fast & powerful event analysis platform"
author: interwaremx
language: en
timezone: UTC

url: https://interwaremx.github.io/caudal.docs
root: /caudal.docs/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy

highlight:
  enable: true
  line_number: false

# disqus_shortname: hexojs
# google_analytics: UA-48498357-3

twitter: caudal_iw
github: interwaremx/caudal
